---
- name: this is tes4 for installing webpkg
  hosts: all
  become: true
  tasks:
  - name: installing web pkg
    yum:
       name: httpd
       state: installed
    notify: start httpd service

  
  handlers:
  - name: start httpd service
    service:
     name: httpd
     state: started
